blacklist:
  - Hub
  - Keyboard
  - Card Reader
  - USB Host Controller
  - USB High-Speed Bus
  - FaceTime Camera
  - FaceTime HD Camera
  - IR Receiver

list_path: 'public/usb_list.json'
inventory_path: 'public/inventory.json'
  